# Generated by Django 6.0.6 on 2026-07-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_processingjob_progress_alter_processingjob_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingjob',
            name='output_file',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
