# Generated by Django 6.0.6 on 2026-07-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_processingjob_output_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingjob',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='processingjob',
            name='filename',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='processingjob',
            name='output_file',
            field=models.FileField(blank=True, null=True, upload_to='processed/'),
        ),
        migrations.AlterField(
            model_name='processingjob',
            name='status',
            field=models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='QUEUED', max_length=20),
        ),
    ]
