services:

  frontend:
    build: ./frontend
    container_name: react_frontend

    command: npm run dev -- --host 0.0.0.0

    ports:
      - "5173:5173"

    volumes:
      - ./frontend:/app
      - /app/node_modules

    depends_on:
      - django

    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL:-http://localhost:8000/api}


  django:
    build: ./backend
    container_name: django_backend

    command: python manage.py runserver 0.0.0.0:8000

    ports:
      - "8000:8000"

    volumes:
      - ./backend:/app

    depends_on:
      - redis

    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4.1-mini}

      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY:-django-insecure-local-development-key}
      - DJANGO_DEBUG=${DJANGO_DEBUG:-True}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS:-localhost,127.0.0.1}

      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS:-http://localhost:5173}
      - CSRF_TRUSTED_ORIGINS=${CSRF_TRUSTED_ORIGINS:-http://localhost:5173}


  redis:
    image: redis:7-alpine
    container_name: redis_server

    ports:
      - "6379:6379"


  celery:
    build: ./backend
    container_name: celery_worker

    command: celery -A config worker --loglevel=info

    volumes:
      - ./backend:/app

    depends_on:
      - redis

    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4.1-mini}


  flower:
    build: ./backend
    container_name: flower_dashboard

    command: celery -A config flower

    ports:
      - "5555:5555"

    volumes:
      - ./backend:/app

    depends_on:
      - redis
      - celery

    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0