services:

  frontend:
    build: ./frontend
    container_name: react_frontend

    command: npm run dev -- --host 0.0.0.0

    ports:
      - "5173:5173"

    volumes:
      - ./frontend:/app
      - /app/node_modules

    depends_on:
      - django


  django:
    build: ./backend
    container_name: django_backend

    command: python manage.py runserver 0.0.0.0:8000

    ports:
      - "8000:8000"

    volumes:
      - ./backend:/app

    depends_on:
      - redis

    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0


  redis:
    image: redis:7-alpine
    container_name: redis_server

    ports:
      - "6379:6379"


  celery:
    build: ./backend
    container_name: celery_worker

    command: celery -A config worker --loglevel=info

    volumes:
      - ./backend:/app

    depends_on:
      - redis

    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0


  flower:
    build: ./backend
    container_name: flower_dashboard

    command: celery -A config flower

    ports:
      - "5555:5555"

    volumes:
      - ./backend:/app

    depends_on:
      - redis
      - celery

    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0